development:
  adapter: postgresql
  encoding: unicode
  database: odin-kittens_development
  pool: 5
  username: baracus

test:
  adapter: postgresql
  encoding: unicode
  database: odin-kittens_test
  pool: 5
  username: baracus

production:
  adapter: postgresql
  encoding: unicode
  database: odin-kittens_production
  pool: 5
  username: baracus
